Repository diem/explorer, pull requests merged in 2021-12, with the labels that each got.

#85 Display Total mint amount, total burn amount and total net amount in current statistics card
  end2end/Landing_test.js
  end2end/wiremock/mappings/analyticsApi/postForLatestDiemInCirculationAggregate.json
  src/Pages/LandingPage/LandingPage.test.tsx
  src/Pages/LandingPage/LandingPage.tsx
  src/api_clients/AnalyticsQueries.ts
  utils/Analytics_Hasura_Api_Zeus_Client/zeus/const.ts
  utils/Analytics_Hasura_Api_Zeus_Client/zeus/index.ts
Labels: enhancement

#90 Display historical graph of XUS in circulation values
  end2end/DiemInCirculation_test.js
  end2end/wiremock/mappings/analyticsApi/postForDiemInCirculationHistory.json
  end2end/wiremock/mappings/analyticsApi/postForXDXInCirculation.json
  end2end/wiremock/mappings/analyticsApi/postForXUSInCirculation.json
  package.json
  src/Pages/DiemInCirculationPage/DiemInCirculationPage.test.tsx
  src/Pages/DiemInCirculationPage/DiemInCirculationPage.tsx
  src/api_clients/AnalyticsQueries.ts
  utils/Analytics_Hasura_Api_Zeus_Client/zeus/const.ts
  utils/Analytics_Hasura_Api_Zeus_Client/zeus/index.ts
  yarn.lock
Labels: enhancement, Page: Diem in Circulation

#99 Add Makefile documentation to README
  README.md
Labels: documentation

#101 Render each component of the Account page as data becomes available
  src/Pages/AccountPage/AccountPage.test.tsx
  src/Pages/AccountPage/AccountPage.tsx
  src/Pages/AccountPage/Balances.tsx
  src/Pages/AccountPage/SmartContractMethods.tsx
  src/Pages/AccountPage/SmartContractStructs.tsx
Labels: Page: Account Details

#103 Capitalize custom types
  src/Pages/AccountPage/AccountPage.tsx
  src/Pages/DiemInCirculationPage/DiemInCirculationPage.test.tsx
  src/Pages/DiemInCirculationPage/DiemInCirculationPage.tsx
  src/Pages/LandingPage/LandingPage.test.tsx
  src/Pages/LandingPage/LandingPage.tsx
  src/api_clients/AnalyticsQueries.ts
Labels: enhancement

#110 Update list of necessary tables and views in README
  README.md
Labels: documentation
